from os import environ

REDDIT_CLIENT_ID = environ['REDDIT_CLIENT_ID']
REDDIT_CLIENT_SECRET = environ['REDDIT_CLIENT_SECRET']
REDDIT_USERNAME = environ['REDDIT_USERNAME']
REDDIT_PASSWORD = environ['REDDIT_PASSWORD']
REDDIT_USER_AGENT = environ['REDDIT_USER_AGENT']
DATABASE_URL = environ['DATABASE_URL']
DATABASE_PASSWORD = environ['DATABASE_PASSWORD']
DATABASE_USERNAME = environ['DATABASE_USERNAME']
