from os import environ

#reddit creds
REDDIT_CLIENT_ID = environ['REDDIT_CLIENT_ID']
REDDIT_CLIENT_SECRET = environ['REDDIT_CLIENT_SECRET']
REDDIT_USERNAME = environ['REDDIT_USERNAME']
REDDIT_PASSWORD = environ['REDDIT_PASSWORD']
REDDIT_USER_AGENT = environ['REDDIT_USER_AGENT']

#database creds
DATABASE_URL = environ['DATABASE_URL']
DATABASE_PASSWORD = environ['DATABASE_PASSWORD']
DATABASE_USERNAME = environ['DATABASE_USERNAME']

#imgur creds
IMGUR_CLIENT_ID = environ['IMGUR_CLIENT_ID']
IMGUR_CLIENT_NAME = environ['IMGUR_CLIENT_NAME']
IMGUR_CLIENT_SECRET = environ['IMGUR_CLIENT_SECRET']

#instagram creds
INSTAGRAM_USERNAME = environ['INSTAGRAM_USERNAME']
INSTAGRAM_PASSWORD = environ['INSTAGRAM_PASSWORD']
